"""create_explore_holdings_table

Revision ID: f05a19c2df60
Revises: b9c8a1d3e5f2
Create Date: 2026-04-01 19:01:20.711930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f05a19c2df60'
down_revision: Union[str, None] = 'b9c8a1d3e5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explore_holdings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('goal_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('scheme_code', sa.String(length=50), nullable=False),
    sa.Column('scheme_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('average_nav', sa.Float(), nullable=False),
    sa.Column('invested_amount', sa.NUMERIC(precision=14, scale=2), nullable=False),
    sa.Column('current_value', sa.NUMERIC(precision=14, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explore_holdings_goal_id'), 'explore_holdings', ['goal_id'], unique=False)
    op.create_index(op.f('ix_explore_holdings_user_id'), 'explore_holdings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explore_holdings_user_id'), table_name='explore_holdings')
    op.drop_index(op.f('ix_explore_holdings_goal_id'), table_name='explore_holdings')
    op.drop_table('explore_holdings')
    # ### end Alembic commands ###
